name: pulseProp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.6
  - numpy=1.26.2
  - scipy=1.11.4
  - pyfftw=0.13.1
  - h5py=3.9.0
  - cxx-compiler
  - fftw=3.3.10
  - cmake=3.22.1
  - make
